name: TelegramAI
description: A simple TelegramAI bot using Dart
version: 1.0.5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  televerse: ^2.4.4
  dotenv: ^4.2.0
  http: ^1.1.0
  hive: ^2.2.3
  intl: ^0.20.2
